### ISSUE TITLE
403 ApolloError

### ISSUE THREAD

**Issue by FerrariAndrea** [plussub/plussub#80]
Hi,
recently I'm not able to use that ext anymore. This is the error:
```
Uncaught (in promise) ApolloError: 403: Forbidden
    at new ApolloError (popup.js:122151:28)
    at popup.js:121395:47
    at both (popup.js:126653:31)
    at popup.js:126642:72
    at new Promise (<anonymous>)
    at Object.then (popup.js:126642:24)
    at Object.next (popup.js:126655:49)
    at notifySubscription (popup.js:129847:18)
    at onNotify (popup.js:129891:3)
    at SubscriptionObserver.next (popup.js:129940:5)
```
Seems that the error came direclty from the Apollo dependencies:
https://github.com/plussub/plussub/blob/576278f925250f7401b179e2a634385ab2b2690b/src/popup/language/store/listContentLanguagesQuery/index.ts#L3

With a fast fix I just handles all the possiblity of fault on the ApolloClient, beacuse in my case I don't need it.
I propose you do handle the possibility that the ApolloClient reject the connection, in order to let work the ext just loading manually the sub file.

You can find the fast fix here: 
https://github.com/plussub/plussub/pull/81

Thx, for your ext

**Comment by ste-xx** [comment]
fixed
